import { APP_NAME_WITH_TM, APP_VERSION } from '@/shared/constants'

export interface ReportSection {
  id: 'results' | 'burnUp' | 'cdf' | 'histogram'
  label: string
  imageDataUrl: string
}

export interface ReportMetadata {
  projectName: string
  generationDate: string
  summaryText: string
}

export function escHtml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
}

export function buildReportHtml(
  sections: ReportSection[],
  metadata: ReportMetadata
): string {
  const sectionsHtml = sections.map((s) => `
    <div class="section">
      <h2>${escHtml(s.label)}</h2>
      <img src="${s.imageDataUrl}" alt="${escHtml(s.label)}" />
    </div>
  `).join('')

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${escHtml(metadata.projectName)} - Forecast Report</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
      color: #1a1a1a;
      background: #ffffff;
      padding: 40px;
      max-width: 1100px;
      margin: 0 auto;
    }
    header {
      border-bottom: 3px solid #0070f3;
      padding-bottom: 16px;
      margin-bottom: 32px;
    }
    header h1 {
      font-size: 1.5rem;
      color: #0070f3;
      margin-bottom: 4px;
    }
    header .meta {
      font-size: 0.85rem;
      color: #666;
    }
    header .summary {
      font-size: 0.9rem;
      color: #333;
      margin-top: 12px;
      line-height: 1.5;
      font-style: italic;
    }
    .section {
      margin-bottom: 32px;
      page-break-inside: avoid;
    }
    .section h2 {
      font-size: 1.1rem;
      color: #0070f3;
      margin-bottom: 12px;
      padding-bottom: 4px;
      border-bottom: 1px solid #e5e7eb;
    }
    .section img {
      max-width: 100%;
      height: auto;
      display: block;
    }
    footer {
      margin-top: 40px;
      padding-top: 12px;
      border-top: 1px solid #e5e7eb;
      font-size: 0.75rem;
      color: #999;
      text-align: center;
    }
    @media print {
      body { padding: 20px; }
      .section { page-break-inside: avoid; }
      footer { position: fixed; bottom: 0; left: 0; right: 0; }
    }
  </style>
</head>
<body>
  <header>
    <h1>${escHtml(metadata.projectName)}</h1>
    <div class="meta">Generated ${escHtml(metadata.generationDate)}</div>
    <div class="summary">${escHtml(metadata.summaryText)}</div>
  </header>
  ${sectionsHtml}
  <footer>Generated by ${escHtml(APP_NAME_WITH_TM)} v${escHtml(APP_VERSION)}</footer>
</body>
</html>`
}

export function openForecastReport(
  sections: ReportSection[],
  metadata: ReportMetadata
): void {
  const html = buildReportHtml(sections, metadata)
  const w = window.open('', '_blank')
  if (!w) {
    throw new Error('Pop-up blocked. Please allow pop-ups for this site.')
  }
  w.document.write(html)
  w.document.close()
}
