import { describe, it, expect } from 'vitest'
import { escHtml, buildReportHtml, type ReportSection, type ReportMetadata } from './generate-report'

describe('escHtml', () => {
  it('escapes ampersands', () => {
    expect(escHtml('A & B')).toBe('A &amp; B')
  })

  it('escapes angle brackets', () => {
    expect(escHtml('<script>alert("xss")</script>')).toBe('&lt;script&gt;alert(&quot;xss&quot;)&lt;/script&gt;')
  })

  it('escapes double quotes', () => {
    expect(escHtml('He said "hello"')).toBe('He said &quot;hello&quot;')
  })

  it('returns empty string unchanged', () => {
    expect(escHtml('')).toBe('')
  })

  it('passes through plain text unchanged', () => {
    expect(escHtml('Hello World 123')).toBe('Hello World 123')
  })

  it('handles multiple special characters together', () => {
    expect(escHtml('1 < 2 & 3 > 2 "ok"')).toBe('1 &lt; 2 &amp; 3 &gt; 2 &quot;ok&quot;')
  })
})

describe('buildReportHtml', () => {
  const metadata: ReportMetadata = {
    projectName: 'Test Project',
    generationDate: '2026-02-10',
    summaryText: 'Forecast summary text.',
  }

  const section: ReportSection = {
    id: 'results',
    label: 'Forecast Results',
    imageDataUrl: 'data:image/png;base64,abc123',
  }

  it('returns valid HTML document', () => {
    const html = buildReportHtml([section], metadata)
    expect(html).toContain('<!DOCTYPE html>')
    expect(html).toContain('</html>')
  })

  it('includes project name in title and header', () => {
    const html = buildReportHtml([section], metadata)
    expect(html).toContain('<title>Test Project - Forecast Report</title>')
    expect(html).toContain('<h1>Test Project</h1>')
  })

  it('includes generation date', () => {
    const html = buildReportHtml([section], metadata)
    expect(html).toContain('Generated 2026-02-10')
  })

  it('includes summary text', () => {
    const html = buildReportHtml([section], metadata)
    expect(html).toContain('Forecast summary text.')
  })

  it('includes section heading and image', () => {
    const html = buildReportHtml([section], metadata)
    expect(html).toContain('<h2>Forecast Results</h2>')
    expect(html).toContain('src="data:image/png;base64,abc123"')
    expect(html).toContain('alt="Forecast Results"')
  })

  it('includes multiple sections in order', () => {
    const sections: ReportSection[] = [
      { id: 'results', label: 'Results', imageDataUrl: 'data:1' },
      { id: 'burnUp', label: 'Burn-Up', imageDataUrl: 'data:2' },
    ]
    const html = buildReportHtml(sections, metadata)
    const resultsIdx = html.indexOf('<h2>Results</h2>')
    const burnUpIdx = html.indexOf('<h2>Burn-Up</h2>')
    expect(resultsIdx).toBeLessThan(burnUpIdx)
  })

  it('handles empty sections array', () => {
    const html = buildReportHtml([], metadata)
    expect(html).toContain('<h1>Test Project</h1>')
    expect(html).not.toContain('<h2>')
  })

  it('includes footer with app name and version', () => {
    const html = buildReportHtml([section], metadata)
    expect(html).toContain('Generated by SPERT')
    expect(html).toContain('footer')
  })

  it('escapes HTML in project name', () => {
    const xssMetadata = { ...metadata, projectName: '<img onerror=alert(1)>' }
    const html = buildReportHtml([section], xssMetadata)
    expect(html).not.toContain('<img onerror')
    expect(html).toContain('&lt;img onerror=alert(1)&gt;')
  })

  it('escapes HTML in section labels', () => {
    const xssSection: ReportSection = { id: 'results', label: '<b>Bold</b>', imageDataUrl: 'data:x' }
    const html = buildReportHtml([xssSection], metadata)
    expect(html).not.toContain('<b>Bold</b>')
    expect(html).toContain('&lt;b&gt;Bold&lt;/b&gt;')
  })

  it('includes print styles', () => {
    const html = buildReportHtml([section], metadata)
    expect(html).toContain('@media print')
    expect(html).toContain('page-break-inside: avoid')
  })
})
